<?php

return array(
    array(
        'name'    => 'ws_url',
        'title'   => '公网WS地址',
        'type'    => 'string',
        'content' => array(),
        'value'   => 'wss://your.site/wss/',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '浏览器直连的公网 WebSocket 地址，生产环境必须使用 wss://',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'port',
        'title'   => '监听端口',
        'type'    => 'string',
        'content' => array(),
        'value'   => '8283',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '常驻服务本机监听端口',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'register_address',
        'title'   => 'Register地址',
        'type'    => 'string',
        'content' => array(),
        'value'   => '127.0.0.1:1236',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'GatewayWorker 内部 Register 地址，单机部署保持默认即可',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'heartbeat',
        'title'   => '心跳秒数',
        'type'    => 'string',
        'content' => array(),
        'value'   => '25',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '建议前端心跳间隔秒数，通过配置接口返回给前端',
        'ok'      => '',
        'extend'  => '',
    ),
);
